server:
  port: 8082
spring:
  application:
    name: consumer
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    data-username: root
    password: password
mybatis:
  type-aliases-package: cn.itcast.pojo
eureka:
  client:
    service-url: # EurekaServer地址,多个地址以','隔开
      defaultZone: http://127.0.0.1:8083/eureka
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds:3000