server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    data-username: root
    password: password
  application:
    name: user-service
mybatis:
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url: # EurekaServer地址,多个地址以','隔开
      defaultZone: http://127.0.0.1:8083/eureka

  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90