server:
  port: 8085
spring:
  application:
    name: gateway2
eureka:
  client:
    service-url: # EurekaServer地址,多个地址以','隔开
      defaultZone: http://127.0.0.1:8083/eureka
zuul:
  ignored-services:
    - user-service