server:
  port: 8083
spring:
  application:
    name: Eureka-server
#eureka:
#  client:
#    service-url: # EurekaServer地址,多个地址以','隔开
#      defaultZone: http://127.0.0.1:8083/eureka,
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false